apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-svc
  name: app-svc
spec:
  ports:
  - name: alunos-api
    port: 8600
    protocol: TCP
    targetPort: 8600
  selector:
    app: alunos-api
  type: NodePort
status:
  loadBalancer: {}
